[package]
name = "parquet-parser"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.102"
bytes = "1.11.1"
thrift = { version = "0.17.0", default-features = false }

[dev-dependencies]
arrow = "58.1.0"
parquet = { version = "58.1.0", default-features = false, features = ["arrow"] }
