[book]
title = "Write yourself a parquet parser"
authors = ["Khanh Duong"]
language = "en"

[output.html]
additional-css = ["custom.css"]
site-url = "/write-you-a-parquet-parser/"

[output.html.playground]
runnable = false
